### PR TITLE
Remove untrue statement about `@last` support

### LINKED ISSUE #82: Supporting `@last` for object iteration
Hi,

The doc of built-in `#each` has the following assertion:

> When iterating over an object only the `@first` is available.

I believe that this assertion is not true since 2014 ([this commit](https://github.com/handlebars-lang/handlebars.js/commit/3a9440f954092558275cd4c05a35ba34bcbfa210)).

It is true that some implementation have not implemented this by default (see [my ticket](https://github.com/Handlebars-Net/Handlebars.Net/issues/480) for .NET), but please consider updating the assertion.

Thanks,
Yehoshua

### PR DESCRIPTION
**Pull request by jaylinski**
This feature was implemented in https://github.com/handlebars-lang/handlebars.js/commit/3a9440f954092558275cd4c05a35ba34bcbfa210.

Resolves #82

### CODE REVIEW

**Comment by nknapp** [comment]
@Afanyiyu could you have a look it the chinese translation of the change is correct?

**Review by nknapp — APPROVED** [review]

**Comment by Afanyiyu** [comment]
df850e8

**Review by Afanyiyu — APPROVED** [review]

**Review by yoshigev — APPROVED** [review]
Thanks!

**Comment by jaylinski** [comment]
@Afanyiyu Thanks!

**Pull request merged**
