### PR TITLE
Add Chinese Translations / 添加中文翻译

### PR DESCRIPTION
**Pull request by Afanyiyu**
While maintaining rigor, I've tried to make the documentation easy to understand.
I'll try to make them better.

### CODE REVIEW

**Comment by Afanyiyu** [comment]
!Why failed,,,,,
Let me check,,,,,

**Comment by nknapp** [comment]
Nice. But it is really necessary to duplicate all the examples?

Are you really going to translate the example values as well?

**Comment by nknapp** [comment]
I'll merge this to master to see how it looks like.

**Comment by nknapp** [comment]
https://handlebars-preview.knappi.org/

**Comment by Afanyiyu** [comment]
moji

...Yes as you mentioned, it isn't necessary to translate the values of the examples.
But I've met a bug that once someone clicks in the example page in the Chinese mode, it will rollback the whole app to English as the `examples` folder is in the root of the `src`, so the VuePress considers it as a part of English Documents.

But actually, it's language-neutral.
Maybe one possible solution is that moving all the documents of English into the `en` folder but that will cause other problems and we need English remaining the default language of the site.

So I duplicate all the examples into the `src/zh/examples` folder to avoid accidental language switching by VuePress.

moji

Maybe there's better way to solve this...

**Pull request merged**
