### PR TITLE
Tweaked Wording

### PR DESCRIPTION
**Pull request by KennyOliver**
It also said, "to order to". 
I initially changed that to "in order to", 
but then just got rid of the whole "to order" thing.

### CODE REVIEW

**Comment by nknapp** [comment]
are you sure that capitalizing words is correct in english? I am a native german speaker, so I am not sure. But in the english translations that I am working on, we usually write every in small letters, except the first letter of the sentence.

**Comment by papasmile** [comment]
Hi, All, to chime in as a native English speaker and webmaster... 
* That wording change is more succinct and makes sense
* Capitalization of proper nouns (i.e. GitHub) is correct
* Title case for button actions is an older web style that has fallen out of use.  Take our PR for e.g., it has "Merge pull request" and "Close with comment" buttons.  Call to action buttons are typically in regular sentence case nowadays

**Comment by nknapp** [comment]
@papasmile just stumbled across this PR. What do you think? 

* Should we close it?
* Was your last comment ("Title case for button actions...") meant as a change request to @KennyOliver ?

**Comment by papasmile** [comment]
Hi, @nknapp, yea, I guess that last point was more of a change request but wanted to answer all your queries.  Didn't hear back from OP, but I can wait a couple weeks, apply my suggestions, then merge if we don't hear back...

**Comment by papasmile** [comment]
Superseded by https://github.com/handlebars-lang/docs/pull/150

**Pull request closed without merging**
