### PR TITLE
Add "Precompiling templates" documentation page

### PR DESCRIPTION
**Pull request by 76784**
Content copied from "old" documentation, run through Turndown,
and polished.

### CODE REVIEW

**Comment by nknapp** [comment]
I am sorry if you had a lot of work with this, but I had closed the issue 8 days ago after copying and rewriting that page and putting it into the "installation" section. Maybe you can look and see of anything is missing there or if it is too hard too find, but a complete rewrite is not needed anymore.

**Comment by 76784** [comment]
Oh, so it's in the Git source code, but not up on the web yet? No biggie, as I didn't spend a lot of time on it, bu you might want to make note of that in places where you have a help wanted communication, like here: https://handlebars-draft.knappi.org/topics/precompilation.html

**Comment by nknapp** [comment]
OK. I actually moved the site.to a new domain. (Preview instead of draft). The changes should also be on "draft", but I guess you service worker is still caching it. 

After the site is open for a while, a popup should appearance, asking you to refresh it.

**Comment by nknapp** [comment]
Amyway, I hope to go live soon (waiting for wycats to make the DNS changes). So the domains will change soon again

**Pull request closed without merging**
