### PR TITLE
Add Korean Translation for Handlebars.js Documentation

### PR DESCRIPTION
**Pull request by Myunwoo**
Description:
This PR adds a complete Korean translation of the Handlebars.js documentation. The translated content includes all sections of the original documentation, ensuring that Korean-speaking developers can easily understand and utilize Handlebars.js.

Changes:
Added a new directory src/ko with all translated files.
Updated the main documentation page to include a link to the Korean version.

Checklist:
 ☑️ All translated files are included.
 ☑️ Links to the Korean documentation are correctly placed.
 ☑️ Reviewed for accuracy and completeness.

Thank you for considering this PR.

### CODE REVIEW

**Comment by papasmile** [comment]
Awesome!  Are there any Korean-speakers who can review out there?

**Comment by Myunwoo** [comment]
Is there anyone who can review what I translated? If not, I can ask developers around me.

I'm curious about what process a review should take.

**Comment by papasmile** [comment]
Hi, sure, it can be informal.  Some should proof-read and suggest any corrections, or say if everything looks good; more that one person would be even better :)

**Comment by Seongjunsim** [comment]
I have been asked to review a Korean translation document, and here are the results of my review.
In the markdown file, line breaks result in spaces being applied.
Therefore, line breaks should be applied where spaces are needed.

Here is an example:
src/ko/guide
- 대 체됩니다 -> 대체됩니다
- 이스케이프하지 않 습니다. -> 이스케이프하지 않습니다.
- 이스케 이프되지 않도록 -> 이스케이프되지 않도록
- 않 더라도 -> 않더라도
- 템플 릿을 -> 템플릿을

src/ko/guide
- 이는 표 현식이라고 -> 이는 표현식이라고

Apart from the spacing errors, there are no awkward parts in the translation.

**Comment by Myunwoo** [comment]
@Seongjunsim Spacing error has been corrected. Thank you for your review.

**Comment by sungsuhan** [comment]
I reviewed the revised version. There doesn't seem to be any problem.

**Comment by Myunwoo** [comment]
/ko/index.md file
::: playground [Live Demo →](/ko/playground.md) :::

The above contents 

::: playground
[Live Demo →](playground.md)
:::

If I commit and push with line breaks as shown above, it is saved without line breaks. What should I do? I need help.

**Comment by papasmile** [comment]
@Myunwoo hm usually a local git client issue, try reading that one: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by Myunwoo** [comment]
@papasmile Tahnk you so much!
If the line break wasn't done properly, it was possible to solve the problem by adding two spaces at the end of the line.
I'll ask for a review again to see if there are any problems with my contribution.

**Comment by sungsuhan** [comment]
I reviewed the revised version. All translated sentences have been checked, including modifications to the demo button.
It doesn't look like a problem to me!

**Review by jaylinski — APPROVED** [review]

**Comment by papasmile** [comment]
thanks!

**Comment by papasmile** [comment]
Korean translation is now live at https://handlebarsjs.com/ko/

**Pull request merged**
